name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          # Use YOUR GitHub App token
          github_token: ${{ steps.app-token.outputs.token }}
          
          # AWS Bedrock configuration with Claude Opus 4.1
          use_bedrock: "true"
          timeout_minutes: "60"
          mode: "tag"
          
          # Claude Opus 4.1 environment settings
          claude_env: |
            AWS_REGION=us-east-1
            AWS_BEDROCK_MODEL_ID=us.anthropic.claude-opus-4-1-20250805-v1:0
            ANTHROPIC_MODEL=us.anthropic.claude-opus-4-1-20250805-v1:0
          
          # Custom instructions for better performance
          custom_instructions: |
            You are helping with the n8n_hr_viragames_automation project.
            This project integrates TeamTailor, BambooHR, and Notion for HR automation.
            Be direct, practical, and focus on solving problems efficiently.
            When reviewing code, prioritize security, maintainability, and performance.
